version: "3.9"
services:
  postgres:
    container_name: sliftd_db
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "SL_INTERNATIONAL_FOODS_LTD"
      POSTGRES_USER: "root_admin"
      POSTGRES_PASSWORD: "Z0h1!b8*s4$"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - slifltd-db-data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root_admin -d SL_INTERNATIONAL_FOODS_LTD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sliftd_api
    environment:
        DB_HOST : 'sliftd_db'
        DB_USER :  'root_admin'
        DB_PSWD :  'Z0h1!b8*s4$' 
        DB_NAME : 'SL_INTERNATIONAL_FOODS_LTD'
        DB_PORT : '5432'
        JWT_SECRET : 'SLJHWJFhcawihqwi*32t28923479273932hdsauohdao128305ska'
    ports:
      - '3000:3000'

    volumes:
      - ./src:/app/src
    networks:
    - postgres      

  pgadmin:
    container_name: pg_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres    

volumes:
  slifltd-db-data:
  pgadmin-data:
networks:
  postgres:
    driver: bridge  